// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafR-Xrs7tHZfVVOLGhEFowsdiJyDa4sY',
    appId: '1:886737043713:web:e909ab75b4e6d4a61b9b00',
    messagingSenderId: '886737043713',
    projectId: 'healthcare-31ca1',
    authDomain: 'healthcare-31ca1.firebaseapp.com',
    storageBucket: 'healthcare-31ca1.appspot.com',
    measurementId: 'G-KST8SQEPHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpTIxgsIYuRI5RVJrraZxCccCFX95OzWI',
    appId: '1:886737043713:android:ec256ffccce914e31b9b00',
    messagingSenderId: '886737043713',
    projectId: 'healthcare-31ca1',
    storageBucket: 'healthcare-31ca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG07Yp9HnSAWuT3qQCT73oyC84Kg38Iqo',
    appId: '1:886737043713:ios:c5fecc76c9f11c061b9b00',
    messagingSenderId: '886737043713',
    projectId: 'healthcare-31ca1',
    storageBucket: 'healthcare-31ca1.appspot.com',
    iosClientId: '886737043713-qp9fquopgcu6c17kvovfmcsrrcol3h4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG07Yp9HnSAWuT3qQCT73oyC84Kg38Iqo',
    appId: '1:886737043713:ios:c5fecc76c9f11c061b9b00',
    messagingSenderId: '886737043713',
    projectId: 'healthcare-31ca1',
    storageBucket: 'healthcare-31ca1.appspot.com',
    iosClientId: '886737043713-qp9fquopgcu6c17kvovfmcsrrcol3h4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBafR-Xrs7tHZfVVOLGhEFowsdiJyDa4sY',
    appId: '1:886737043713:web:e61949b665e469391b9b00',
    messagingSenderId: '886737043713',
    projectId: 'healthcare-31ca1',
    authDomain: 'healthcare-31ca1.firebaseapp.com',
    storageBucket: 'healthcare-31ca1.appspot.com',
    measurementId: 'G-BLXJZEGHNJ',
  );
}
